version: "2"
services:

  airportal:
    build: ./nginx
    container_name: airportal
    ports:
      - "8000:80"
    depends_on:
      - trackservice
      - gmapswrapper

  trackservice:
    build: ./trackservice
    container_name: trackservice

  gmapswrapper:
    build: ./gmapswrapper
    container_name: gmapswrapper

networks:
  default:
    external:
      name: airnet
