version: "3"
services:
  web:
    build: ./nginx
    networks:
      - airnet
    ports:
      - "8000:80"
  trackservice:
    build: ./trackservice
    environment:
      - POSTGRES_USER=luliu
      - POSTGRES_PASS=luliu
      - POSTGRES_DBNAME=tracksdb
      - ALLOW_IP_RANGE=0.0.0.0/0
    networks:
      - airnet
    ports:
      - "8001:8001"
    volumes:
      - pgdata:/var/lib/postgresql
  gmapswrapper:
    build: ./gmapswrapper
    networks:
      - airnet
    ports:
      - "8002:8002"

networks:
  airnet:

volumes:
  pgdata:
